FROM node:12-alpine as build
# working directory
WORKDIR /usr/src/app
ENV NODE_ENV=production

RUN apk --no-cache --virtual add \
    python \
    make \
    g++ \
    yarn

COPY . ./

RUN yarn install --frozen-lockfile

RUN yarn run build
RUN chown -R node:node /usr/src/app

USER node
EXPOSE 8080

CMD [ "yarn", "start" ]
