export enum CustomerModalTypes {
    LOG_IN = 'LOG_IN',
    PASSWORD_RECOVERY = 'PASSWORD_RECOVERY'
    // PASSWORD_RECOVERY_SUCCESS = 'PASSWORD_RECOVERY_SUCCESS',
    // DELETE_ACCOUNT = 'DELETE_ACCOUNT'
}
